### ISSUE TITLE
How to run pytest

### ISSUE THREAD

**Issue by hoangquochung1110** [MtScience/PyLox#20]
Hi, thank you for your project

I've cloned it and run your unit tests with pytest but got this error:
```
python3.10/site-packages/_pytest/config/__init__.py:329: PluggyTeardownRaisedWarning: A plugin raised an exception during an old-style hookwrapper teardown.
Plugin: helpconfig, Hook: pytest_cmdline_parse
ConftestImportFailure: ModuleNotFoundError: No module named 'pylox' (from /path/to/PyLox/test/conftest.py)
For more information see https://pluggy.readthedocs.io/en/stable/api_reference.html#pluggy.PluggyTeardownRaisedWarning
  config = pluginmanager.hook.pytest_cmdline_parse(
ImportError while loading conftest '/path/to/PyLox/test/conftest.py'.
test/conftest.py:3: in <module>
    from pylox import Lox
E   ModuleNotFoundError: No module named 'pylox'
```

Do I have to set up or configure anything else to get it up and running ?

Thank you a lot

**Comment by MtScience** [comment]
Hello, Hoàng! Thanks for your feedback. I hope you find my little project useful.

I personally ran my tests from my IDE (PyCharm, to be precise), where it worked just fine. I've just tried running them from Windows command line and indeed, I got that same error. Apparently, PyCharm uses some paths-related magic. I did this to fix the error:
* added `__init__.py` to `/PyLox/src/`;
* prefixed all imports (except libraries) with dots (e.g. `from .expr import *` instead of `from expr import *`);
* changed the import in `conftest.py` from `from pylox import ...` to `from src.pylox import ...`;
* prefixed all the paths in test files with `./test` (e.g. `lox.run_file("./test/for/class_in_body.lox")` instead of `lox.run_file("for/class_in_body.lox")`);
* ran the tests with
  ```
  python -m pytest test
  ```
  with venv activated.
After this it worked fine. Please let me know if it solved the issue for you.

Best regards.

P. S. Sorry, if I got your name wrong—I'm not familiar with Vietnamese names.

**Comment by hoangquochung1110** [comment]
Hi,

I'm quite surprised by PyCharm doing some magic in the background to find import paths. (In the meanwhile, I'm using vscode)
Your changes also worked for me, thank you for quick response.

On the other hand,
given this import:

> from expr import *

I can say that your style of import seems incorrect. Because if you run `python -m pytest` at project directory (`path/to/PyLox`), the interpreter has no idea if `expr` is a submodule or a built-in package. Therefore it raised `ModuleNotFoundError`

I think the import code style should be in either form as below:
1. `from .expr import *`
2. `from src.expr import *` (we may rename `src` to sth like `pylox` for more meaningfull naming)

Finally, thank you for the contribution. We usually start our projects with help of some frameworks like Django or IDEs like PyCharm. They do some magic but we're hardly aware of. Today I learn more about module/package importing in Python.

**Comment by MtScience** [comment]
Hi again.

I'm glad it worked for you! Seems like I'll have to update the code a little bit. Thanks for pointing out this problem.

Best regards.
